/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : DIO.c
**     Project   : ZJM_M32
**     Processor : MC9S08SH8MTJ
**     Component : BitIO
**     Version   : Component 02.075, Driver 03.24, CPU db: 3.00.065
**     Compiler  : CodeWarrior HCS08 C Compiler
**     Date/Time : 2022/3/5, 15:46
**     Abstract  :
**         This component "BitIO" implements an one-bit input/output.
**         It uses one bit/pin of a port.
**         Methods of this component are mostly implemented as a macros
**         (if supported by target language and compiler).
**     Settings  :
**         Used pin                    :
**             ----------------------------------------------------
**                Number (on package)  |    Name
**             ----------------------------------------------------
**                       8             |  PTB4_TPM2CH1_MISO
**             ----------------------------------------------------
**
**         Port name                   : PTB
**
**         Bit number (in port)        : 4
**         Bit mask of the port        : $0010
**
**         Initial direction           : Input (direction can be changed)
**         Safe mode                   : yes
**         Initial output value        : 0
**         Initial pull option         : up
**
**         Port data register          : PTBD      [$0002]
**         Port control register       : PTBDD     [$0003]
**
**         Optimization for            : speed
**     Contents  :
**         SetDir    - void DIO_SetDir(bool Dir);
**         SetInput  - void DIO_SetInput(void);
**         SetOutput - void DIO_SetOutput(void);
**         GetVal    - bool DIO_GetVal(void);
**         PutVal    - void DIO_PutVal(bool Val);
**         ClrVal    - void DIO_ClrVal(void);
**         SetVal    - void DIO_SetVal(void);
**
**     Copyright : 1997 - 2010 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

/* MODULE DIO. */

#include "DIO.h"
  /* Including shared modules, which are used in the whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
#include "Cpu.h"


/*
** ===================================================================
**     Method      :  DIO_GetVal (component BitIO)
**
**     Description :
**         This method returns an input value.
**           a) direction = Input  : reads the input value from the
**                                   pin and returns it
**           b) direction = Output : returns the last written value
**     Parameters  : None
**     Returns     :
**         ---             - Input value. Possible values:
**                           FALSE - logical "0" (Low level)
**                           TRUE - logical "1" (High level)

** ===================================================================
*/
/*
bool DIO_GetVal(void)

**  This method is implemented as a macro. See DIO.h file.  **
*/

/*
** ===================================================================
**     Method      :  DIO_PutVal (component BitIO)
**
**     Description :
**         This method writes the new output value.
**           a) direction = Input  : sets the new output value;
**                                   this operation will be shown on
**                                   output after the direction has
**                                   been switched to output
**                                   (SetDir(TRUE);)
**           b) direction = Output : directly writes the value to the
**                                   appropriate pin
**     Parameters  :
**         NAME       - DESCRIPTION
**         Val             - Output value. Possible values:
**                           FALSE - logical "0" (Low level)
**                           TRUE - logical "1" (High level)
**     Returns     : Nothing
** ===================================================================
*/
void DIO_PutVal(bool Val)
{
  if (Val) {
    setReg8Bits(PTBD, 0x10);           /* PTBD4=0x01 */
    Shadow_PTB |= (byte)0x10;          /* Set-up shadow variable */
  } else { /* !Val */
    clrReg8Bits(PTBD, 0x10);           /* PTBD4=0x00 */
    Shadow_PTB &= (byte)~0x10;         /* Set-up shadow variable */
  } /* !Val */
}

/*
** ===================================================================
**     Method      :  DIO_ClrVal (component BitIO)
**
**     Description :
**         This method clears (sets to zero) the output value.
**           a) direction = Input  : sets the output value to "0";
**                                   this operation will be shown on
**                                   output after the direction has
**                                   been switched to output
**                                   (SetDir(TRUE);)
**           b) direction = Output : directly writes "0" to the
**                                   appropriate pin
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void DIO_ClrVal(void)

**  This method is implemented as a macro. See DIO.h file.  **
*/

/*
** ===================================================================
**     Method      :  DIO_SetVal (component BitIO)
**
**     Description :
**         This method sets (sets to one) the output value.
**           a) direction = Input  : sets the output value to "1";
**                                   this operation will be shown on
**                                   output after the direction has
**                                   been switched to output
**                                   (SetDir(TRUE);)
**           b) direction = Output : directly writes "1" to the
**                                   appropriate pin
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void DIO_SetVal(void)

**  This method is implemented as a macro. See DIO.h file.  **
*/

/*
** ===================================================================
**     Method      :  DIO_SetDir (component BitIO)
**
**     Description :
**         This method sets direction of the component.
**     Parameters  :
**         NAME       - DESCRIPTION
**         Dir        - Direction to set (FALSE or TRUE)
**                      FALSE = Input, TRUE = Output
**     Returns     : Nothing
** ===================================================================
*/
void DIO_SetDir(bool Dir)
{
  if (Dir) {
    setReg8(PTBD, (getReg8(PTBD) & (~0x10)) | (Shadow_PTB & 0x10)); /* PTBD4=Shadow_PTB[bit 4] */
    setReg8Bits(PTBDD, 0x10);          /* PTBDD4=0x01 */
  } else { /* !Dir */
    clrReg8Bits(PTBDD, 0x10);          /* PTBDD4=0x00 */
  } /* !Dir */
}

/*
** ===================================================================
**     Method      :  DIO_SetInput (component BitIO)
**
**     Description :
**         This method sets direction of the component to input.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void DIO_SetInput(void)

**  This method is implemented as a macro. See DIO.h file.  **
*/

/*
** ===================================================================
**     Method      :  DIO_SetOutput (component BitIO)
**
**     Description :
**         This method sets direction of the component to output.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void DIO_SetOutput(void)
{
  setReg8(PTBD, (getReg8(PTBD) & (~0x10)) | (Shadow_PTB & 0x10)); /* PTBD4=Shadow_PTB[bit 4] */
  setReg8Bits(PTBDD, 0x10);            /* PTBDD4=0x01 */
}


/* END DIO. */
/*
** ###################################################################
**
**     This file was created by Processor Expert 3.09 [04.41]
**     for the Freescale HCS08 series of microcontrollers.
**
** ###################################################################
*/
