/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : us.h
**     Project   : ZJM_M32
**     Processor : MC9S08SH8MTJ
**     Component : FreeCntr
**     Version   : Component 01.115, Driver 01.11, CPU db: 3.00.065
**     Compiler  : CodeWarrior HCS08 C Compiler
**     Date/Time : 2022/3/14, 17:01
**     Abstract  :
**         This device "FreeCntr" implements a free running counter for
**         time measurement.
**     Settings  :
**         Timer name                  : TPM2 (16-bit)
**         Compare name                : TPM20
**         Counter shared              : No
**
**         High speed mode
**             Prescaler               : divide-by-16
**             Clock                   : 1000000 Hz
**           Period
**             Xtal ticks              : 2048
**             microseconds            : 65535
**             milliseconds            : 66
**             seconds (real)          : 0.065535
**             Hz                      : 15
**           Frequency of counting (Bus clock / prescaler)
**             Hz                      : 1000000
**
**         Initialization:
**              Timer                  : Enabled
**
**         Timer registers
**              Counter                : TPM2CNT   [$0061]
**              Mode                   : TPM2SC    [$0060]
**              Run                    : TPM2SC    [$0060]
**              Prescaler              : TPM2SC    [$0060]
**              Compare                : TPM2C0V   [$0066]
**
**         User handling procedure     : not specified
**     Contents  :
**         Reset           - byte us_Reset(void);
**         GetCounterValue - byte us_GetCounterValue(us_TTimerValue *Value);
**
**     Copyright : 1997 - 2010 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

#ifndef __us
#define __us

/* MODULE us. */

/* Include shared modules, which are used for whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
/* Include inherited components */
#include "Cpu.h"

/* PUBLISHED CONSTANTS */
#define us_COUNTER_INPUT_CLOCK_HZ     0x000F4240UL /* Initial counter input clock frequency [Hz] */
#define us_PERIOD_VALUE               0xFFFFUL /* Initial period value in ticks of the timer */
#define us_PRESCALER_VALUE           0x10U /* Prescaler value of the timer in high speed mode */
#define us_TIMER_INPUT_CLOCK         0x00F42400UL /* Deprecated, Initial timer input clock value [Hz] */
#define us_UP_COUNTER                1 /* The timer counts upwards */
/* High speed mode constants */
#define us_COUNTER_INPUT_CLOCK_HZ_HIGH 0x000F4240UL /* Counter input clock frequency in high speed mode [Hz] */
#define us_PERIOD_VALUE_HIGH          0xFFFFUL /* Period value in ticks of the timer in high speed mode */
#define us_PRESCALER_VALUE_HIGH      0x10U /* Prescaler value of the timer in high speed mode */
#define us_TIMER_INPUT_CLOCK_HIGH    0x00F42400UL /* Deprecated, Initial timer input clock value [Hz] */

typedef word us_TTimerValue;           /* Counter or compare value, width depends on timer width */

#define us_Reset() ( \
  TPM2CNTH = 0x00,                     /* Reset HW Counter */ \
  (byte)ERR_OK                         /* Return result */ \
)
/*
** ===================================================================
**     Method      :  us_Reset (component FreeCntr)
**
**     Description :
**         This method resets the timer-counter (sets to zero for
**         up-counting HW or to appropriate value for down-counting HW).
**         The method is available only if the counter register can be
**         set by software and the counter is not shared.
**     Parameters  : None
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/

#define us_GetCounterValue(Value) ( \
  *(Value) = TPM2CNT,                  /* Set the flag "events disabled" */ \
  (byte)ERR_OK                         /* Return result */ \
)
/*
** ===================================================================
**     Method      :  us_GetCounterValue (component FreeCntr)
**
**     Description :
**         This method returns a content of the counter.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * Value           - Pointer to returned value.
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/

void us_Init(void);
/*
** ===================================================================
**     Method      :  us_Init (component FreeCntr)
**
**     Description :
**         Initializes the associated peripheral(s) and the component 
**         internal variables. The method is called automatically as a 
**         part of the application initialization code.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/


/* END us. */

#endif /* ifndef __us */
/*
** ###################################################################
**
**     This file was created by Processor Expert 3.09 [04.41]
**     for the Freescale HCS08 series of microcontrollers.
**
** ###################################################################
*/
