/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : Vectors.c
**     Project   : ZJM_M32
**     Processor : MC9S08SH8MTJ
**     Version   : Component 01.007, Driver 01.38, CPU db: 3.00.065
**     Compiler  : CodeWarrior HCS08 C Compiler
**     Date/Time : 2022/3/5, 15:46
**     Abstract  :
**         This component "MC9S08SH8_20" contains initialization 
**         of the CPU and provides basic methods and events for 
**         CPU core settings.
**     Settings  :
**
**
**     Copyright : 1997 - 2010 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/


#include "Cpu.h"
#include "STB.h"
#include "DIO.h"
#include "CLK.h"
#include "Relay1.h"
#include "Relay2.h"
#include "Relay3.h"
#include "Relay4.h"
#include "SDA2.h"
#include "SDA1.h"
#include "T20ms.h"
#include "AD.h"
#include "us.h"
#include "IFsh1.h"
#include "WDog.h"
#include "Alarm.h"
extern near void _EntryPoint(void);

void (* near const _vect[])(void) @0xFFC0 = { /* Interrupt vector table */
         Cpu_Interrupt,                /* Int.no. 31 VReserved31 (at FFC0)           Unassigned */
         Cpu_Interrupt,                /* Int.no. 30 Vacmp (at FFC2)                 Unassigned */
         Cpu_Interrupt,                /* Int.no. 29 VReserved29 (at FFC4)           Unassigned */
         Cpu_Interrupt,                /* Int.no. 28 VReserved28 (at FFC6)           Unassigned */
         Cpu_Interrupt,                /* Int.no. 27 VReserved27 (at FFC8)           Unassigned */
         Cpu_Interrupt,                /* Int.no. 26 Vmtim (at FFCA)                 Unassigned */
         Cpu_Interrupt,                /* Int.no. 25 Vrtc (at FFCC)                  Unassigned */
         Cpu_Interrupt,                /* Int.no. 24 Viic (at FFCE)                  Unassigned */
         AD_Interrupt,                 /* Int.no. 23 Vadc (at FFD0)                  Used */
         Cpu_Interrupt,                /* Int.no. 22 VReserved22 (at FFD2)           Unassigned */
         Cpu_Interrupt,                /* Int.no. 21 Vportb (at FFD4)                Unassigned */
         Cpu_Interrupt,                /* Int.no. 20 Vporta (at FFD6)                Unassigned */
         Cpu_Interrupt,                /* Int.no. 19 VReserved19 (at FFD8)           Unassigned */
         Cpu_Interrupt,                /* Int.no. 18 Vscitx (at FFDA)                Unassigned */
         Cpu_Interrupt,                /* Int.no. 17 Vscirx (at FFDC)                Unassigned */
         Cpu_Interrupt,                /* Int.no. 16 Vscierr (at FFDE)               Unassigned */
         Cpu_Interrupt,                /* Int.no. 15 Vspi (at FFE0)                  Unassigned */
         Cpu_Interrupt,                /* Int.no. 14 Vtpm2ovf (at FFE2)              Unassigned */
         Cpu_Interrupt,                /* Int.no. 13 Vtpm2ch1 (at FFE4)              Unassigned */
         Cpu_Interrupt,                /* Int.no. 12 Vtpm2ch0 (at FFE6)              Unassigned */
         Cpu_Interrupt,                /* Int.no. 11 Vtpm1ovf (at FFE8)              Unassigned */
         Cpu_Interrupt,                /* Int.no. 10 VReserved10 (at FFEA)           Unassigned */
         Cpu_Interrupt,                /* Int.no.  9 VReserved9 (at FFEC)            Unassigned */
         Cpu_Interrupt,                /* Int.no.  8 VReserved8 (at FFEE)            Unassigned */
         Cpu_Interrupt,                /* Int.no.  7 VReserved7 (at FFF0)            Unassigned */
         Cpu_Interrupt,                /* Int.no.  6 Vtpm1ch1 (at FFF2)              Unassigned */
         T20ms_Interrupt,              /* Int.no.  5 Vtpm1ch0 (at FFF4)              Used */
         Cpu_Interrupt,                /* Int.no.  4 VReserved4 (at FFF6)            Unassigned */
         Cpu_Interrupt,                /* Int.no.  3 Vlvd (at FFF8)                  Unassigned */
         Cpu_Interrupt,                /* Int.no.  2 Virq (at FFFA)                  Unassigned */
         Cpu_Interrupt,                /* Int.no.  1 Vswi (at FFFC)                  Unassigned */
         _EntryPoint                   /* Int.no.  0 Vreset (at FFFE)                Reset vector */
};
/*
** ###################################################################
**
**     This file was created by Processor Expert 3.09 [04.41]
**     for the Freescale HCS08 series of microcontrollers.
**
** ###################################################################
*/

